--1
SELECT E.FIRST_NAME, E.HIRE_DATE, E.SALARY, D.DEPARTMENT_NAME, J.JOB_TITLE
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND E.JOB_ID=J.JOB_ID
AND E.SALARY>=4500
AND E.SALARY<15000;

--2
SELECT E.EMPLOYEE_ID, E.LAST_NAME, C.COUNTRY_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, JOBS J
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND E.JOB_ID=J.JOB_ID
AND UPPER(J.JOB_TITLE)='ACCOUNTANT';

--3
SELECT E
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND (UPPER(L.CITY)='MEXICO CITY' OR UPPER(C.COUNTRY_NAME)='UNITED STATES OF AMERICA');

--4
SELECT E
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND UPPER(D.DEPARTMENT_NAME)='SALES'
AND UPPER(C.COUNTRY_NAME)='UNITED KINGDOM';

--5
SELECT E.FIRST_NAME, E.LAST_NAME FROM REGIONS R
INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
INNER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE UPPER(R.REGION_NAME) = 'AMERICAS'
AND (J.MIN_SALARY+J.MAX_SALARY)/2>E.SALARY;

--6
SELECT R.REGION_NAME,C.COUNTRY_NAME,COUNT(E.EMPLOYEE_ID) 
FROM REGIONS R
INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
INNER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY R.REGION_NAME,C.COUNTRY_NAME HAVING COUNT(E.EMPLOYEE_ID)>3;

--7
SELECT MAX(E.HIRE_DATE)-MIN(E.HIRE_DATE) AS DAYS
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND UPPER(D.DEPARTMENT_NAME) != 'EXECUTIVE';

--8
SELECT S.MANAGER_ID,E.FIRST_NAME,E.LAST_NAME,COUNT(S.MANAGER_ID) 
FROM EMPLOYEES S 
INNER JOIN EMPLOYEES E ON S.MANAGER_ID = E.EMPLOYEE_ID
GROUP BY S.MANAGER_ID,E.FIRST_NAME,E.LAST_NAME
HAVING COUNT(S.MANAGER_ID)<8;

--9
SELECT 'El empleado '|| E.FIRST_NAME ||' ' || E.LAST_NAME ||
' ha trabajado por ' || EXTRACT(YEAR FROM AGE(CURRENT_DATE,E.HIRE_DATE)) ||
' anios ' || EXTRACT(MONTH FROM AGE(CURRENT_DATE,E.HIRE_DATE))|| ' meses y '||
EXTRACT(DAY FROM AGE(CURRENT_DATE,E.HIRE_DATE))  || ' dias.'
FROM REGIONS R
INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
INNER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
INNER JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE UPPER(R.REGION_NAME) = 'EUROPE'	
AND EXTRACT(YEAR FROM E.HIRE_DATE) >= 1997;

--10
SELECT EMPLOYEE_ID,JOB_ID,START_DATE,END_DATE||' ' AS END_DATE FROM JOB_HISTORY
UNION	
SELECT E.EMPLOYEE_ID, E.JOB_ID, MAX(JH.END_DATE) AS START_DATE, NULL AS END_DATE
FROM EMPLOYEES E
INNER JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID=JH.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID, E.JOB_ID
UNION
SELECT E.EMPLOYEE_ID, E.JOB_ID, E.HIRE_DATE AS FIRST_DATE, NULL AS END_DATE
FROM EMPLOYEES E LEFT JOIN JOB_HISTORY JB
ON E.EMPLOYEE_ID = JB.EMPLOYEE_ID WHERE JB.EMPLOYEE_ID IS NULL
ORDER BY EMPLOYEE_ID,START_DATE

--11
CREATE TABLE emp001 AS SELECT LPAD(CAST(E.EMPLOYEE_ID AS VARCHAR),8,'0') AS EMPLOYEE_ID, 
UPPER(E.FIRST_NAME) AS FIRST_NAME, UPPER(E.LAST_NAME) AS LAST_NAME, D.DEPARTMENT_NAME, 
UPPER(MA.FIRST_NAME)||' '||UPPER(MA.LAST_NAME) AS MANAGER_NAME 
FROM EMPLOYEES E, DEPARTMENTS D, EMPLOYEES MA
WHERE E.SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES)
AND E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND E.MANAGER_ID=MA.EMPLOYEE_ID;
